#!/bin/bash
echo "=== Diagnostic Report ==="
echo ""
echo "1. Check .env file:"
test -f /home/appuser/hospital-app/incodefy/.env && echo ".env exists" || echo ".env missing"
echo ""
echo "2. Check node_modules:"
test -d /home/appuser/hospital-app/incodefy/node_modules && echo "node_modules exists" || echo "node_modules missing"
echo ""
echo "3. Check PM2 processes:"
sudo -u appuser bash -c "export HOME=/home/appuser && pm2 list"
echo ""
echo "4. Check port 3000:"
netstat -tlnp 2>/dev/null | grep :3000 || echo "Nothing on port 3000"
echo ""
echo "5. Try starting server manually:"
cd /home/appuser/hospital-app/incodefy
sudo -u appuser bash -c "export HOME=/home/appuser && cd /home/appuser/hospital-app/incodefy && NODE_ENV=production node server.js &"
sleep 5
echo ""
echo "6. Check port 3000 again:"
netstat -tlnp 2>/dev/null | grep :3000 || echo "Still nothing on port 3000"
echo ""
echo "7. Check logs if available:"
test -f /home/appuser/pm2-app.log && tail -20 /home/appuser/pm2-app.log || echo "No PM2 log"
